#!/bin/bash 
# For study // convert following from c to java
# https://android.googlesource.com/platform/system/core/+/master/libcrypto_utils/android_pubkey.c


# JUST EXECUTE This File with root permission 

rm bin/*.class
rm executable.jar

javac -d bin CMain.java P11RSAKeyPair.java
#java -cp bin CMain

cd bin
jar cvmf MAINFEST.MF executable.jar *.class
mv executable.jar ../
cd ..
chmod 774 executable.jar
chown administrator:administrator executable.jar

